### ISSUE TITLE
NTR: Request for L05 telecommunication_facility

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/L05#22]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>telecommunication_facility <p><b>Definition</b><p> Entity or part of entity that enables telecommunication or can be utilized for telecommunication purposes  (e.g. via satellite internet constellation, by cell phones, optical fiber, or alike).<p><H2> Optional </H2><p><b>ORCID</b><p> 0000-0003-0367-6850<p>

**Comment by nanselm** [comment]
hi, 

what's the schedule on issues?  this (and another one) is untouched for several weeks.

**Comment by gwemon** [comment]
Sorry @nanselm this might have been missed on my watch. It's now logged in our systems. We will be back to you if required.

**Comment by nanselm** [comment]
no worries, thanks for notifying. we are curious what is the general workflow (from here on). we (pangaea, marum, awi, +x) are planning for more. is this the preferred way? any obstacles or things to care about??

**Comment by gwemon** [comment]
For just a few terms, github requests to the specific repo are fine but if you envisage a large volume of requests then it would be best if we talk it through in a quick meeting. Also please be aware that each term proposed need to fit the existing coverage of the existing vocabulary and requires careful consideration by the governance team. Some are more straightforward than others. I suspect that the term you are proposing here might require discussion. We have a team of people dedicated to managing instruments and platforms vocabularies. In order to provide more info could you give us some examples of the kind of instrument models you would see fitting in this category? Also would "telecomnunication devices" or "telecommunication equipment" be a better term?

**Comment by nanselm** [comment]
The task group is on the way to harmonize the vocabularies in use in different systems and environments. This includes a lot discussion and everything that might be submitted has undergone some kind of review internally. At first we just care for devices and plan to have concise actions, such as development sprints. But this will take some time until we have agreed on a common workflow across the institutions. If I got our schedule right we intend to contact BODC anyway. 

Regarding this term:  we tried to have the definition as generic as possible. Typical devices would be starlink systems, oneweb, kongsberg marine broadcast systems, mobile gateways or smartphones used as modems in a measuring container (you know what I mean?). We omitted "devices" and chose "facility" because sometimes it is rather a bunch of things instead of a single device -- more a system. E.g. starlink has the antenna and a router box, the kongsberg mbr consist of an antenna, a massive 19" power unit and a computer. But we are open to discuss on this term suggestion. :D

**Comment by gwemon** [comment]
Thank you @nanselm that's useful info. 
We already have a number of "systems" defined at the L05 level so this would probably be preferable to "facility" but let's see what the L05 management group thinks. @danibodc or @louatbodc or somebody else from the team will be in touch after the Easter break.

**Comment by nanselm** [comment]
sounds wonderful. thank you and happy holidays.

**Comment by louatbodc** [comment]
Hi @nanselm 

We think this request might be timely given the evolution of Internet of Things. We suggest 'systems' given that some modems are combined with sensors (such as Arduino boards). We propose the following:

Telemetry systems
Systems that transmit data remotely to receiving systems through communication networks (e.g. WIFI, cellular phone or satellite networks) and communication protocols such as HTTP and MQTT.

**Comment by LennertSchepers** [comment]
In my opinion tele**metry** involves a kind of measurement (doesn't require communication, data can also be stored on a device) so is different from tele**communication**. The description is only about the transfer of data so maybe *telecommunication systems* is better?

**Comment by pieterhaaring** [comment]
For the L05 list the scope is "Terms used to classify groups of sensors, instruments, sources of algorithmically computed data (numerical models) or samplers (collectors of water, SPM, sediment, rock, air or biota samples)"

"Telemetry" or "the science or process of collecting information about objects that are far away and sending the information somewhere electronically" does not fit within this scope.

**Comment by roy-lowry** [comment]
The description of this category has semantically drifted since I last looked.  I have concerns about the addition of protocols as this would dictate that 'HTTP' is a valid L22 entry, which makes me very uncomfortable. I would suggest a description along the lines of:

'Devices or systems that transmit data from one geographic location to another (e.g. WIFI, cellular phone or satellite networks)' 
'Telecommunication Systems' conveys a clear meaning to me and includes kit such as Iridium that are obviously within L05/L22 scope. I'm far less certain about the meaning of 'Telemetry Systems'.

**Comment by danibodc** [comment]
Thanks for everyone's feedback and apologies for letting this drop off the radar. We have now loaded the following L05 category and it will be live on the NVS from tomorrow morning:

398	telecommunication systems
'Devices or systems that transmit data from one geographic location to another (e.g. WIFI, cellular phone or satellite networks)'

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/L05/current/398/
