### ISSUE TITLE
NTR: Request for L05 Integrated CTD pH O2 Instrument (BODCNVS-1849)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/L05#26]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Integrated CTD pH O2 Instrument <p><b>Definition</b><p> The integrated CTD pH O2 Instrument allows for pH measurements to be combined with critical oceanographic and biological measurements of temperature, salinity, and oxygen.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://www.seabird.com/seaphox-v2/product?id=60762467725 <p> <b>ORCID</b><p> 0000-0001-7218-1232<p> <b>Mapping to other terminologies </b><p> http://vocab.nerc.ac.uk/collection/L22/current/TOOL1895/<p>

**Comment by SLBlakeman** [comment]
The L05 terms are used to classify groups of sensors, instruments, etc. The L22 terms, such as the TOOL1895, can be linked to many L05 terms in order to identify all of the capabilities of the sensor/instrument/etc. For this reason we do not think it would be appropriate to create an L05 term integrating various, already existing L05 terms. If we were to start doing this, it could lead to an increase in workload for the vocabulary team and create confusion when coming to assign an L05 to an L22, with likely little benefit to the community.
I hope this makes sense, please let us know if you have any questions or concerns.
